package com.incorps.indonesiancollege;

import java.util.ArrayList;

public class UniversityData {
    public static University undip = new University( "Universitas Diponegoro", R.drawable.img_undip,"Universitas Diponegoro disingkat Undip, adalah sebuah Perguruan Tinggi Negeri di Indonesia yang berlokasi di Semarang, Jawa Tengah, Indonesia. Undip didirikan pada tahun 1956 sebagai Perguruan Tinggi Swasta dan baru mendapat status sebagai Perguruan Tinggi Negeri pada tahun 1961. Kata Diponegoro diambil dari nama pahlawan nasional, yaitu Pangeran Diponegoro yang merupakan seorang pangeran pengobar semangat kemerdekaan dari tindakan kolonialisme Belanda di awal abad ke-18.", "Fakultas Hukum, Fakultas Ekonomika dan Bisnis, Fakultas Kedokteran, Fakultas Teknik, Fakultas Ilmu Budaya, Fakultas Kesehatan Masyarakat, Fakultas Sains dan Matematika, Fakultas Ilmu Sosial dan Ilmu Politik, Fakultas Peternakan dan Pertanian, Fakultas Perikanan dan Ilmu Kelautan, Fakultas Psikologi, Sekolah Vokasi, Sekolah Pascasarjana", "Jl. Prof.H.Soedarto S.H, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275", "https://www.undip.ac.id");
    public static University ui = new University("Universitas Indonesia", R.drawable.img_ui, "Universitas Indonesia disingkat sebagai UI, adalah sebuah perguruan tinggi di Indonesia. Kampus utamanya terletak di bagian Utara dari Depok, Jawa Barat tepat di perbatasan antara Depok dengan wilayah Jakarta Selatan, dan kampus utama lainnya terdapat di daerah Salemba di Jakarta Pusat. Universitas Indonesia adalah kampus modern, komprehensif, terbuka, multibudaya, dan humanis yang mencakup disiplin ilmu yang luas. Telah menghasilkan lebih dari 400.000 alumni. Secara umum dianggap sebagai salah satu dari tiga perguruan tinggi papan atas di Indonesia bersama dengan Universitas Gadjah Mada dan Institut Teknologi Bandung.", "Fakultas Kedokteran, Fakultas Kedokteran Gigi, Fakultas Farmasi, Fakultas Kesehatan Masyarakat, Fakultas Ilmu Keperawatan, Fakultas Matematika dan Ilmu Pengetahuan Alam, Fakultas Teknik, Fakultas Ilmu Komputer, Fakultas Hukum, Fakultas Ekonomi dan Bisnis, Fakultas Ilmu Pengetahuan Budaya, Fakultas Psikologi, Fakultas Ilmu Sosial dan Ilmu Politik, Fakultas Ilmu Administrasi, Sekolah Ilmu Lingkungan, Sekolah Kajian Stratejik dan Global, Program Vokasi", "Jl. Margonda Raya, Pondok Cina, Kecamatan Beji, Kota Depok, Jawa Barat 16424", "https://www.ui.ac.id/");
    public static University ugm = new University("Universitas Gadjah Mada", R.drawable.img_ugm, "Universitas Gadjah Mada (disingkat UGM) merupakan universitas negeri di Indonesia yang didirikan oleh Pemerintah Republik Indonesia pada tanggal 19 Desember 1949 berdasarkan Peraturan Pemerintah Nomor 23 Tahun 1949 tentang Peraturan Tentang Penggabungan Perguruan Tinggi Menjadi Universiteit tanggal 16 Desember 1949. Kampus UGM yang terletak di Yogyakarta merupakan universitas pertama yang didirikan oleh Pemerintah Republik Indonesia setelah Indonesia merdeka.","Fakultas Biologi, Fakultas Ekonomika dan Bisnis, Fakultas Farmasi, Fakultas Filsafat, Fakultas Geografi, Fakultas Hukum, Fakultas Ilmu Budaya, Fakultas Ilmu Sosial dan Ilmu Politik, Fakultas Kedokteran, Kesehatan Masyarakat, dan Keperawatan (FKKMK), Fakultas Kedokteran Gigi, Fakultas Kedokteran Hewan, Fakultas Kehutanan, Fakultas MIPA (Matematika dan Ilmu Pengetahuan Alam), Fakultas Pertanian, Fakultas Peternakan, Fakultas Psikologi, Fakultas Teknik, Fakultas Teknologi Pertanian, Sekolah Vokasi", "Bulaksumur, Caturtunggal, Kec. Depok, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55281", "https://um.ugm.ac.id");
    public static University itb = new University("Institut Teknologi Bandung", R.drawable.img_itb, "Institut Teknologi Bandung (ITB) adalah sebuah perguruan tinggi negeri yang berkedudukan di Kota Bandung. Nama ITB diresmikan pada tanggal 2 Maret 1959. Sejak tanggal 14 Oktober 2013 ITB menjadi Perguruan Tinggi Negeri Badan Hukum (PTN BH) yang memiliki otonomi pengelolaan dalam akademik dan nonakademik. ITB telah memiliki 27 program studi yang terakreditasi secara internasional (sebelas dari ABET, sebelas dari ASIIN).", "Fakultas Matematika dan Ilmu Pengetahuan Alam (FMIPA), Sekolah Ilmu dan Teknologi Hayati (SITH), Sekolah Farmasi (SF), Fakultas Ilmu dan Teknologi Kebumian (FITB), Fakultas Teknik Pertambangan dan Perminyakan (FTTM), Fakultas Teknologi Industri (FTI), Fakultas Teknik Mesin dan Dirgantara (FTMD), Sekolah Teknik Elektro dan Informatika (STEI), Fakultas Teknik Sipil dan Lingkungan (FTSL), Sekolah Arsitektur, Perencanaan dan Pengembangan Kebijakan (SAPPK), Fakultas Seni Rupa dan Desain (FSRD), Fakultas Seni Rupa dan Desain (FSRD)", "Jl. Ganesha No.10, Lb. Siliwangi, Kecamatan Coblong, Kota Bandung, Jawa Barat 40132", "https://www.itb.ac.id/");
    public static University its = new University("Institut Teknologi Sepuluh Nopember", R.drawable.img_its,"Institut Teknologi Sepuluh Nopember (disingkat ITS) adalah perguruan tinggi negeri yang terletak di Surabaya. ITS awalnya didirikan oleh Yayasan Perguruan Tinggi Teknik (YPTT) yang diketuai oleh dr. Angka Nitisastro pada tanggal 10 November 1957.", "Fakultas Teknologi Industri (FTI), Fakultas Teknologi Kelautan (FTK), Fakultas Teknologi Elektro (FTE), Fakultas Teknik Sipil, Lingkungan, Dan Kebumian (FTSLK), Fakultas Teknologi Informasi Dan Komunikasi (FTIK), Fakultas Arsitektur, Desain, Dan Perencanaan (FADP), Fakultas Sains, Fakultas Matematika, Komputasi, Dan Sains Data (FMKS), Fakultas Vokasi, Fakultas Bisnis Dan Manajemen Teknologi (FBMT)", "Jl. Raya ITS, Keputih, Kec. Sukolilo, Kota SBY, Jawa Timur 60111", "https://www.its.ac.id");
    public static University ipb = new University("Institut Pertanian Bogor", R.drawable.img_ipb, "Institut Pertanian Bogor (nama bahasa Inggris: IPB University, sebelumnya Bogor Agricultural University) adalah sebuah perguruan tinggi pertanian negeri yang berkedudukan di Bogor.  Sebelum diresmikan pada tahun 1963, IPB adalah sebuah fakultas pertanian pada Universitas Indonesia. Pada tanggal 1 September 1963.[3] Presiden Pertama Indonesia, Ir. Soekarno, melakukan peletakkan batu pertama pembangunan kampus sekaligus menandai peresmian Institut Pertanian Bogor sebagai sebuah perguruan tinggi mandiri.", "Fakultas Pertanian, Fakultas Kedokteran Hewan, Fakultas Perikanan dan Ilmu Kelautan, Fakultas Peternakan, Fakultas Kehutanan, Fakultas Teknologi Pertanian, Fakultas Matematika dan Ilmu Pengetahuan Alam, Fakultas Ekonomi dan Manajemen, Fakultas Ekologi Manusia, Sekolah Pascasarjana, Sekolah Bisnis, Program Diploma", "Kampus IPB Dramaga, Jl. Raya Dramaga, Babakan, Dramaga, Babakan, Kec. Dramaga, Bogor, Jawa Barat 16680", "https://www.ipb.ac.id/");
    public static University ub = new University("Universitas Brawijaya", R.drawable.img_ub, "Universitas Brawijaya (UB) adalah perguruan tinggi di Indonesia yang berdiri pada tahun 1963 di Kota Malang, Jawa Timur melalui Ketetapan Menteri Pendidikan dan Ilmu Pengetahuan no.1 tanggal 5 Januari 1963. Tanggal tersebut kemudian ditetapkan sebagai Dies Natalis UB. Nama Brawijaya diberikan khusus oleh Presiden Soekarno dengan harapan mampu gemilang seperti Raden Wijaya (Brawijaya I) selaku pendiri Kerajaan Majapahit sekaligus menjadi kampus kebanggan bangsa Indonesia.", "Fakultas Pertanian (FP UB), Fakultas Peternakan (FAPET UB), Fakultas Perikanan dan Ilmu Kelautan (FPIK UB), Fakultas Teknologi Pertanian (FTP UB), Fakultas Ekonomi dan Bisnis (FEB UB), Fakultas Ilmu Administrasi (FIA UB), Fakultas Teknik (FT UB), Fakultas Matematika dan Ilmu Pengetahuan Alam (FMIPA UB), Fakultas Ilmu Komputer (FILKOM UB), Fakultas Kedokteran (FK UB), Fakultas Kedokteran Hewan (FKH UB), Fakultas Kedokteran Gigi (FKG UB), Fakultas Hukum (FH UB), Fakultas Ilmu Sosial dan Ilmu Politik (FISIP UB), Fakultas Ilmu Budaya (FIB UB), Sekolah Pascasarjana Multidispliner (Pascasarjana Brawijaya), Pendidikan Vokasi (Vokasi UB)", "Jl. Veteran Malang, Ketawanggede, Kec. Lowokwaru, Kota Malang, Jawa Timur 65145", "http://www.ub.ac.id/");
    public static University uns = new University("Universitas Sebelas Maret", R.drawable.img_uns, "Universitas Sebelas Maret biasa disingkat sebagai UNS adalah salah satu universitas negeri di Indonesia yang berada di Kota Solo. Universitas yang giat membangun ini, menyediakan berbagai paket pendidikan diploma, sarjana, pascasarjana, dan doktoral.", "Fakultas Seni Rupa dan Desain, Fakultas Ilmu Budaya, Fakultas Kedokteran Universitas Sebelas Maret, Fakultas Ekonomi dan Bisnis, Fakultas Ilmu Sosial dan Ilmu Politik Universitas Sebelas Maret, Fakultas Keguruan dan Ilmu Pendidikan, Fakultas Matematika dan Ilmu Pengetahuan Alam, Fakultas Pertanian, Fakultas Teknik, Fakultas Hukum", "Jl. Ir Sutami No.36 A, Pucangsawit, Kec. Jebres, Kota Surakarta, Jawa Tengah 57126", "https://uns.ac.id/");
    public static University usk = new University("Universitas Syiah Kuala", R.drawable.img_usk, "Universitas Syiah Kuala (disingkat Unsyiah) adalah perguruan tinggi negeri di Banda Aceh, Indonesia, yang berdiri pada 2 September 1961. Universitas ini terletak di Banda Aceh, tepatnya di Kota Pelajar dan Mahasiswa (disingkat Kopelma), Darussalam. Kampus Unsyiah berjarak 8 km ke arah timur Kota Banda Aceh, 22 km dari Bandara Sultan Iskandar Muda, dan 10 km dari Pelabuhan Malahayati di Krueng Raya.", "Kedokteran, Kedokteran Hewan, Matematika dan Ilmu Pengetahuan Alam, Pertanian, Teknik, Ekonomi dan Bisnis, Hukum", "Jl. Tgk. Hasan Krueng Kalee, Kopelma Darussalam, Kec. Syiah Kuala, Kota Banda Aceh, Aceh 23111", "https://unsyiah.ac.id/");
    public static University unair = new University("Universitas Airlangga", R.drawable.img_unair, "Universitas Airlangga (disingkat UNAIR) adalah sebuah perguruan tinggi negeri yang terletak di Gubeng, Surabaya, Surabaya, Jawa Timur. Universitas ini didirikan tanggal 10 November 1954 bertepatan dengan hari pahlawan yang ke-9. Berdasarkan data 30 September 2015, terdapat 38.047 mahasiswa yang terdaftar di Unair.", "Fakultas Kedokteran (FK), Fakultas Kedokteran Gigi (FKG), Fakultas Hukum (FH), Fakultas Ekonomi dan Bisnis (FEB), Fakultas Farmasi (FF), Fakultas Kedokteran Hewan (FKH), Fakultas Ilmu Sosial dan Ilmu Politik (FISIP), Fakultas Sains dan Teknologi (FST), Fakultas Kesehatan Masyarakat (FKM), Fakultas Psikologi (FPsi), Fakultas Ilmu Budaya (FIB), Fakultas Keperawatan, Fakultas Perikanan dan Kelautan (FPK), Fakultas Vokasi", "Jl. Airlangga No.4 - 6, Airlangga, Kec. Gubeng, Kota SBY, Jawa Timur 60115", "https://www.unair.ac.id/");
    public static University unhas = new University("Universitas Hasanuddin", R.drawable.img_unhas, "Universitas Hasanuddin, yang kemudian disingkat UNHAS, merupakan sebuah perguruan tinggi negeri di kota Makassar, Provinsi Sulawesi Selatan, Indonesia, yang berdiri pada 10 September 1956. Perguruan tinggi ini semula merupakan pengembangan dari Fakultas Ekonomi Universitas Indonesia ketika Bung Hatta masih menjadi Wakil Presiden. Kampus Unhas semula dibangun di Baraya atau Kampus Baraya. Namun, awal tahun 1980-an, ketika Rektor dijabat Prof. Dr. Ahmad Amiruddin, Kampus Unhas dipindahkan ke Tamalanrea, karena Kampus Baraya sudah berada di tengah kota.", "Fakultas Kedokteran, Fakultas Kedokteran Gigi, Fakultas Farmasi, Fakultas Kesehatan Masyarakat, Fakultas Matematika dan Ilmu Pengetahuan Alam, Fakultas Teknik, Fakultas Kehutanan, Fakultas Peternakan, Fakultas Ilmu Kelautan dan Perikanan, Fakultas Pertanian, Fakultas Hukum, Fakultas Ekonomi dan Bisnis, Fakultas Ilmu Budaya, Fakultas Ilmu Sosial dan Ilmu Politik", "Jl. Perintis Kemerdekaan KM.10, Tamalanrea Indah, Kec. Tamalanrea, Kota Makassar, Sulawesi Selatan 90245", "https://unhas.ac.id/");
    public static University unsri = new University("Universitas Sriwijaya", R.drawable.img_unsri, "Universitas Sriwijaya (disingkat UNSRI) adalah sebuah Perguruan Tinggi Negeri di Sumatra Selatan, Indonesia. Universitas Sriwijaya memiliki sepuluh fakultas dengan dua buah kampus yaitu di Bukit Besar, Kota Palembang dan di Indralaya, Kabupaten Ogan Ilir. Jumlah Alumni Universitas Sriwijaya sampai dengan wisuda ke-114 pada 16 Oktober 2014 sebanyak 96.634 orang Alumni yang terdiri dari: S3 dan Spesialis S2 sebanyak 128 wisudawan, Program Pascasarjana S2/SP1 sebanyak 4.830 wisudawan, Sarjana Strata I sebanyak 73.690 wisudawan serta Program Diploma D3 sebanyak 17.989 wisudawan. Unsri mendapatkan akreditasi A (Amat Baik) yang diberikan oleh Badan Akreditasi Nasional Perguruan Tinggi (BAN-PT).", "Fakultas Ekonomi (FE), Fakultas Hukum (FH), Fakultas Teknik (FT), Fakultas Kedokteran (FK), Fakultas Pertanian (FP), Fakultas Keguruan dan Ilmu Pendidikan (FKIP), Fakultas Ilmu Sosial dan Ilmu Politik (FISIP), Fakultas Matematika dan Ilmu Pengetahuan Alam (FMIPA), Fakultas Ilmu Komputer (FASILKOM), Fakultas Kesehatan Masyarakat (FKM)", "Negara Bukit Besar, Jl. Srijaya Negara, Bukit Lama, Kec. Ilir Bar. I, Kota Palembang, Sumatera Selatan 30139", "http://unsri.ac.id/");
    public static University unpad = new University("Universitas Padjadjaran", R.drawable.img_unpad, "Universitas Padjadjaran (disingkat Unpad) adalah sebuah perguruan tinggi negeri di Bandung, Jawa Barat, Indonesia. Pada 20 Oktober 2014, Universitas ini berubah status menjadi Perguruan Tinggi Negeri Badan Hukum (PTN BH) dari Badan Layanan Umum (BLU). Peresmian itu ditandai dengan peraturan pemerintah (PP) yang ditandatangani mantan Presiden Susilo Bambang Yudhoyono. Penetapan itu didasarkan atas evaluasi kinerja yang dilakukan tim independen yang dibentuk Kementerian Pendidikan dan Kebudayan (Kemendikbud)[2]. Selain itu berdasarkan Keputusan Badan Akreditasi Nasional Perguruan Tinggi (BAN PT) yang ditetapkan pada 16 Januari 2014, Unpad mendapat peringkat A (sangat baik).", "Fakultas Hukum, Fakultas Ekonomi dan Bisnis, Fakultas Kedokteran, Fakultas Matematika dan Ilmu Pengetahuan Alam, Fakultas Kedokteran Gigi, Fakultas Ilmu Budaya, Fakultas Ilmu Sosial dan Ilmu Politik, Fakultas Psikologi, Fakultas Ilmu Komunikasi, Fakultas Keperawatan, Fakultas Perikanan dan Ilmu Kelautan, Fakultas Teknologi Industri Pertanian, Fakultas Farmasi, Fakultas Teknik Geologi, Fakultas Peternakan", "Jl. Raya Bandung Sumedang KM.21, Hegarmanah, Kec. Jatinangor, Kabupaten Sumedang, Jawa Barat 45363", "http://www.unpad.ac.id");
    public static University unud = new University("Universitas Udayana", R.drawable.img_unud, "Universitas Udayana, disingkat UNUD, adalah perguruan tinggi negeri di Bali, Indonesia, yang berdiri pada 29 September 1962. Rektor Universitas Udayana dari tahun 2017-2022 adalah Prof. Dr. dr. Anak Agung Raka Sudewi, Sp.S (K).", "Fakultas Ilmu Budaya, Fakultas Kedokteran, Fakultas Hukum, Fakultas Teknik, Fakultas Pertanian, Fakultas Peternakan, Fakultas Matematika Dan Ilmu Pengetahuan Alam, Fakultas Kedokteran Hewan, Fakultas Ekonomi, Fakultas Teknologi Pertanian, Fakultas Pariwisata, Fakultas Ilmu Sosial dan Ilmu Politik, Fakultas Kelautan dan Perikanan", "Jl. Raya Kampus UNUD, Kampus Bukit Jimbaran, Kuta Selatan, Jimbaran, Kec. Kuta Sel., Kabupaten Badung, Bali 80361", "https://www.unud.ac.id/");

    public static ArrayList<University> getData(){
        ArrayList<University> listUniversity = new ArrayList<>();
        listUniversity.add(undip);
        listUniversity.add(ui);
        listUniversity.add(ugm);
        listUniversity.add(itb);
        listUniversity.add(its);
        listUniversity.add(ipb);
        listUniversity.add(ub);
        listUniversity.add(uns);
        listUniversity.add(usk);
        listUniversity.add(unair);
        listUniversity.add(unhas);
        listUniversity.add(unsri);
        listUniversity.add(unpad);
        listUniversity.add(unud);
        return listUniversity;
    }
}
